### ISSUE TITLE
服务保护和分布式事务

### ISSUE THREAD

**Issue by 2004GIF** [2004GIF/chenzian-shrimp.github.io#6]
# 服务保护
实现步骤：
1. 找出需要进行远程调用的业务

2. 在这个微服务添加 sentinel 的坐标和在配置文件中配上 sentinel的控制地址

   ````xml
    <!-- sentinel 服务保护 -->
    <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    </dependency>
   ````

   ```yaml
   spring:
     cloud:
       sentinel: # 连接 sentinel 控制台
         transport:
           dashboard: 127.0.0.1:8090 # sentinel 控制台地址
         http-method-specify: true   # 将http的请求方法作为sentinel的资源名称的一部分 （  ）
   # 设置 feign 在底层使用 okhttp 并且使用 okhttp 的连接池
   feign:
     okhttp:
       enabled: true
     sentinel:
       enabled: true
   ```

3.  给 client 接口添加  FallBack   

   1. 创建类实现 FallbackFactory<CartClient>

      ```java
      @Slf4j
      public class CartClientFallBack implements FallbackFactory<CartClient> {
          @Override
          public CartClient create(Throwable cause) {
              return ids -> {
                  log.error("批量删除购物车数据 --- 远程调用失败，原因：{}", cause.getMessage());
                  throw new RuntimeException(StrUtil.format("批量删除购物车数据 ：{}", cause.getMessage()));
              };
          }
      }
      ```

   2. 添加到 IOC 容器中

      ```java
         @Bean
          public CartClientFallBack cartClientFallBack() {
              return new CartClientFallBack();
          }
      ```

   3. 在 client 添加 FallBack 

      ```java
      @FeignClient(value = "cart-service" , fallbackFactory = CartClientFallBack.class)
      public interface CartClient {
          /**
           * 批量删除购物车数据
           * @param ids
           */
          @DeleteMapping("/carts")
          void deleteCartItemByIds(@RequestParam("ids") Collection<Long> ids);
      }
      ```

4. 在控制台中添加保护规则  （sentinel ）

# 实现分布式事务
实现步骤：

1. 给每一个加入业务的微服务添加 seata 依赖和对应的seata配置 （  在nacos 中可以直接在 bootstrap 文件引入）
2. 【如果 seata 选择的模式是 AT ，就需要给每一个参加业务的微服务添加一个 undo_log （快照表用于恢复数据）】
3. 给业务入口加上 @GlobalTransactional 注解
4. 给其他被调用的业务加上 @Transactional 注解（明确该业务可能会滚回）
